const ProjectsData = [
    {
        title: 'Market Seasonality Explore',
        description: "Application that visualizes market seasonality through a dynamic calendar UI with daily, weekly, and monthly views. It includes interactive heatmaps for volatility, liquidity indicators, and performance metrics, designed to help traders and analysts explore historical pattern.",
        skills: ['ReactJS', 'NextJS', 'Material UI', 'Recharts'],
        images: ['1.jpeg','2.jpeg','3.jpeg', '4.jpeg','5.jpeg','6.jpeg'],
        githubLink:'https://github.com/dipesh162/Marketing-seasonality-explorer',
        hostedUrl: 'https://marketing-seasonality-explorer.vercel.app/',        
    },
    {
        title: 'Heart Care',
        description: "Developed a fully responsive website for a cardiologist using Next.js and Tailwind CSS.Replicated the design from an archived version of the client’s old site and added updated service information.",
        skills: ['ReactJS', 'NextJS', 'Tailwind CSS'],
        images: ['1.png','2.png','3.png'],
        githubLink:'https://github.com/dipesh162/Heart-Care-Noida',
        hostedUrl: 'https://heart-care-noida-qgl8tgfms-dipesh162.vercel.app/',        
    },
    {
        title: 'Versioned Rich Text Editor',
        description: "A full-featured, collaborative document editor built using TipTap (ProseMirror), designed to support version control and branching timelines. This project demonstrates advanced state management, real-time UI updates, and a creative approach to document versioning and branching workflows in the browser.",
        skills: ['ReactJS', 'TypeScript', 'Vite', 'Tailwind CSS'],
        images: ['1.png','2.png','3.png','4.png'],
        githubLink:'https://github.com/dipesh162/Versioned-Rich-Text-Editor',
        hostedUrl: 'https://versioned-rich-text-editor.vercel.app/'     
    },
    {
        title: 'Movie Browser',
        description: 'Developed a movie browser application using the TMDB API, featuring custom filters for type, popularity, release year, genre, and rating range. The app includes a personalized infinite scrolling implementation, allowing users to explore a wide range of movies effortlessly. Additionally, users can bookmark their favorite movies and TV shows for easy access, enhancing the overall viewing experience.',
        skills: ['ReactJS', 'NextJS', 'NodeJS', 'Tailwind CSS'],
        images: ['1.png','2.png','3.png','4.png','5.png'],
        githubLink:'https://github.com/dipesh162/Movie-Browser',
        hostedUrl: 'https://movie-browser-dipesh162.vercel.app/',        
    },
    {
        title: 'Music Store (E commerce)',
        description: 'A MERN stack ecommerce music store for all music enthusiasts, showcasing variety of string, keyboards, wind and percussive instruments.',
        skills: ['ReactJS', 'NextJS', 'NodeJS', 'ExpressJS', 'MongoDB', 'Tailwind CSS'],
        images: ['1.jpg','2.jpg','3.jpg'],
        githubLink:'https://github.com/dipesh162/Music-Store',
        hostedUrl: 'https://music-store-dipesh162.vercel.app/',
    },
    {
        title: 'Grid CRUD - msw',
        description: 'Created a GRID gallery application where users can create new items with a title and image, edit and delete existing items, and view the time of the last update. To avoid the need for a backend, I implemented CRUD APIs using Mock Service Worker for adding, editing, and deleting items. This project demonstrates my proficiency in managing state and implementing CRUD functionality in a front-end application.',
        skills: ['ReactJS', 'Mock service worker'],
        images: ['1.png','2.png','3.png', '4.png', '5.png', '6.png'],
        githubLink:'https://github.com/dipesh162/Grid-CRUD-msw',
        hostedUrl: 'https://master--grid-crud-msw.netlify.app/',
    },
    {
        title: 'Free Tour Tickets',
        description: 'A website for getting a free concert tickets by uploading sketches/covers of your favourite artists. The site features user and admin panel.',
        skills: ['ReactJS', 'NodeJS', 'ExpressJS', 'EJS', 'Bootstrap'],
        images: ['1.jpg','2.jpg','3.jpg','4.jpg'],
        githubLink:'https://github.com/dipesh162/Free-Tour-Tickets',
        hostedUrl: 'https://freetourtickets.onrender.com/',
    },
    {
        title: 'Chain Calculator',
        description: 'The Function Chain Calculator is a web app built with React and Next.js that lets users chain mathematical functions and calculate results in real-time. It allows adding, removing, and reordering functions dynamically while offering instant feedback and error handling. The app is fully responsive, providing a smooth user experience across devices, and showcases my expertise in building interactive, user-friendly applications with modern web technologies.',
        skills: ['ReactJS', 'NextJS', 'NodeJS', 'Tailwind CSS'],
        images: ['1.jpg','2.jpg','3.jpg'],
        githubLink:'https://github.com/dipesh162/Function-Chain-Calculator',
        hostedUrl: 'https://function-chain-calculator.netlify.app/',      
    },
    {
        title: 'Fifteen Puzzle Game',
        description: 'I developed a 15 Puzzle Game using React, designed to challenge players to arrange tiles in numerical order by moving them within a 4x4 grid. The game features:<ul><li>Timer: Tracks the duration of the game.</li><li>Move Counter: Keeps count of the number of moves made.</li><li>Reset Button: Allows players to restart the game at any time.</li><li>Shuffle Functionality: Randomly shuffles the tiles for a new challenge.</li><li>Next Step Button: Enables progression to subsequent stages or levels.</li><li>This project showcases my skills in React, state management, and interactive UI design.</li></ul>',
        skills: ['ReactJS', 'NextJS', 'NodeJS', 'ExpressJS', 'MongoDB', 'Tailwind CSS'],
        images: ['1.png','2.png'],
        githubLink:'https://github.com/dipesh162/Fifteen-Puzzle-Game',
        hostedUrl: 'https://master--subtle-peony-af4ffb.netlify.app/',
    },
    {
        title: 'Tic Tac Toe',
        description: 'Developed a Tic Tac Toe game using React, which allows users to reset the game at any point. The game dynamically displays the winner and can be stopped to halt gameplay. This project highlights my ability to create interactive and responsive user interfaces with React, ensuring a smooth and engaging gaming experience.',
        skills: ['ReactJS', 'Tailwind CSS'],
        images: ['1.png','2.png'],
        githubLink:'https://github.com/dipesh162/Tic-Tac-Toe',
        hostedUrl: 'https://dipesh-tic-tac-toe.netlify.app/',
    },
    {
        title: 'Restaurant Menu',
        description: ' created a dynamic menu for a London-based restaurant using Tailwind CSS for styling and React Intersection Observer for adding animations and effects. This project showcases my ability to combine modern CSS frameworks and JavaScript libraries to enhance user experience through interactive and visually appealing designs.',
        skills: ['ReactJS', 'Intersection Observer', 'Tailwind CSS'],
        images: ['1.png','2.png','3.png','4.png'],
        githubLink:'https://github.com/dipesh162/restaurant',
        hostedUrl: 'https://friendly-otter-198bf6.netlify.app/',
    },
]

export default ProjectsData